GET http://localhost:8000/api/clients HTTP/1.1
###

POST http://localhost:8000/api/clients HTTP/1.1
Content-Type: application/json

{
    "name": 1,
    "lastname": 2,
    "start_date": 3,
    "type": "regular",
    "subscription": 6
}
###

PUT http://localhost:8000/api/clients/629ca0e64d2c381e28d48368 HTTP/1.1
Content-Type: application/json

{    
    "subscription": 1
}
###

DELETE http://localhost:8000/api/clients/629ca07ae7573cc8b71b1710 HTTP/1.1
Content-Type: application/json

{    
}
###